### PR TITLE
Harmony is now know as "smb_a1002" in the CM repo.

### PR DESCRIPTION
**Pull request by gu1dry**

### CODE REVIEW

**Comment by tonky** [comment]
wtf lol, now THAT would look strange along the device names :)

**Comment by tonky** [comment]
thanks, i'll add it when nightiles will be rolling out

**Comment by gu1dry** [comment]
Well the change is due to the Viewsonic G Tablet is actually the Malata smb_a1002, and Harmony is just the codename of the Tegra2 chipset that it uses.

**Comment by gu1dry** [comment]
I'll just close this since it doesn't seem you're paying attention to my additions.

**Comment by tonky** [comment]
i'll be watching it further manually, not relying on github notifications

**Comment by tonky** [comment]
okay, i've added vivo and will close this. i'll be watching for g tablet nightlies renames, and will pull changes from your patch.

thanks!

**Comment by gu1dry** [comment]
What I'll try to do in the future (if I can figure it out, I'm bit of a git n00b) is try to make each new device a separate pull request.

**Comment by tonky** [comment]
yeah, that would help :)

**Pull request closed without merging**
