### PR TITLE
fix update zip name

### PR DESCRIPTION
**Pull request by swordrune10**
because the name convention has been changed, the site seem to be having a huge list changelog of supposed unbuilt items..

im not really one for writing java, so this may be incorrect..

### CODE REVIEW

**Comment by angelsl** [comment]
This is JavaScript, not Java..

**Comment by swordrune10** [comment]
...really.. gonna be like that? ok well, regardless if its java, javascript, C++, bash, applescript, fortran -- i hope its written ok

**Comment by angelsl** [comment]
I'm testing it now actually. Hold on..

**Comment by swordrune10** [comment]
read on the site that tonky has no motivation to update the site.. =/ gonna leave this open for a week or something..

**Comment by angelsl** [comment]
There's a new site out there now. :/ 

http://changelog.bbqdroid.org/

**Comment by swordrune10** [comment]
ive seen it.. i suppose they carry the torch now.. first it was that google docs spreadsheet, then the app spot one, then bbqdroid.. even with such knowledge i will not go back on my word.. cya in a week i suppose..

**Comment by angelsl** [comment]
I actually revived this for a brief period at http://cm9-nightlies.appspot.com/ but after I found out about bbqdroid, I deleted it.

**Comment by swordrune10** [comment]
what..? does my little patch make it work?

**Comment by angelsl** [comment]
Yes, well, sort of. I modified it a little so it doesn't stop recognising old-style nightly filenames.

It's in [this other pull request](https://github.com/tonky/gae-cm-nightlies/pull/29).

**Comment by swordrune10** [comment]
ah ha.. can i close this and delete the project on my end? would rather not interfere with ur pull request..

**Comment by angelsl** [comment]
if you want, go ahead..

**Pull request closed without merging**
